 
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// // import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// // import { ReactNode, useState } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   //  const [queryClient] = useState(() => new QueryClient());
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* <QueryClientProvider client={queryClient}> */}
//         {children}
//         {/* </QueryClientProvider> */}

//       </body>
//     </html>
//   );
// }

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
//  import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
//  import { ReactNode, useState } from "react";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title:{
//     default: "Next App",
//     template: "%s | Next App",
//   },
//   description: "Generated by create next app",
// };


// // export default function RootLayout({ children }) {
// //   console.log("children" ,  children);
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
        
// //         <nav>navbar</nav>
// //         {/* <h1>Vaibhav Funde </h1> */}
      
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }



// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const [queryClient] = useState(() => new QueryClient());
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <QueryClientProvider client={queryClient}>
//         {children}
//         </QueryClientProvider>

//       </body>
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/provider/providers";
import { Toaster } from "react-hot-toast";
//import { Providers } from "./providers"; // ✅ Add this line

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next App",
    template: "%s | Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
         <Toaster position="top-center" />

          {children}
        </Providers>
      </body>
    </html>
  );
}
